---
# file containing default ggplot2 theme shared across scripts
theme_spec: scripts/spt6_2018_theme_specification.R

figure_one:
    height: 14
    width: 17.4
    ## heatmaps of TSS-seq signal
    one_a:
        sense_tss_data: ../tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-spikenorm-SENSE.tsv.gz
        antisense_tss_data: ../tss-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/spikenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-spikenorm-ANTISENSE.tsv.gz
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
        height: 5/12*17
        width: 12
    # SPT6 western blot
    one_b:
        data_path: ../small-data/spt6-western/SPT6_western_quantification.tsv
        blot_path: ../small-data/spt6-western/spt6-western.png
        height: 5.83
        width: 2.9
    # TSS-seq differential expression double barplot
    one_c:
        genic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-genic-all.tsv
        intragenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-all.tsv
        antisense: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/antisense/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-antisense-all.tsv
        intergenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intergenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intergenic-all.tsv
        height: 5
        width: 8
    # violin plots of expression level and TFIIB signal
    one_d:
        tss_genic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-genic-all.tsv
        tss_intragenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-all.tsv
        tss_antisense: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/antisense/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-antisense-all.tsv
        tss_intergenic: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intergenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intergenic-all.tsv
        # tfiib_genic: ../chipnexus-tfiib/diff_binding/spt6-1004-37C-v-WT-37C/libsizenorm/genic/spt6-1004-37C-v-WT-37C_tfiib-chipnexus-libsizenorm-diffbind-results-genic-all.tsv
        # tfiib_intragenic: ../chipnexus-tfiib/diff_binding/spt6-1004-37C-v-WT-37C/libsizenorm/intragenic/spt6-1004-37C-v-WT-37C_tfiib-chipnexus-libsizenorm-diffbind-results-intragenic-all.tsv
        # tfiib_intergenic: ../chipnexus-tfiib/diff_binding/spt6-1004-37C-v-WT-37C/libsizenorm/intergenic/spt6-1004-37C-v-WT-37C_tfiib-chipnexus-libsizenorm-diffbind-results-intergenic-all.tsv
        width: 7
        height: 6
    # TSS-seq scatterplots
    supp_height: 22
    supp_width: 17.4
    supp_a:
        tss_data: ../tss-seq/qual_ctrl/scatter_plots/tss-seq_union-bedgraph-spikenorm-window-10-allsamples.tsv.gz
        height: "17/12*4"
        width: 12
    # TSS-seq vs malabat
    supp_b:
        tss_data: ../other-datasets/malabat15/figures/verified-transcripts/allsamples-verified-transcripts-SENSE.tsv.gz
        height: 4.25
        width: 6
    supp_c:
        data_path: ../assay-correlations/scores/coding-genes/coding-genes_WT-37C_allassays.tsv
        height: 5
        width: 6
    # histogram of diffexp intragenic starts per ORF
    supp_d:
        intra_diffexp_data: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-up.tsv
        orf_anno: ../genome/annotations/Scer_nondubious_ORFs.bed
        height: 4
        width: 4
    # bvenn of genes with intragenic: us, cheung08, uwimana17
    supp_e:
        diffexp_results: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-up.tsv
        positions: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/position_bias/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-intragenic-up-RELATIVE.tsv
        height: 6
        width: 7
    supp_f:
        common_names: ../other-datasets/spt6-intragenic-genes-comparison/Scer-sys-to-common-name.tsv
        cheung_data: ../other-datasets/cheung08/cheung08-S3.tsv
        uwimana_data: ../other-datasets/uwimana17/uwimana17-S2.tsv
        tss_data: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-up.tsv
        height: 6
        width: 7

figure_two:
    height: 17
    width: 17.4
    # TFIIB heatmaps
    two_a:
        tfiib_data: ../chipnexus-tfiib/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/libsizenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-tfiib-chipnexus-libsizenorm-protection.tsv.gz
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
        height: 5/12*17
        width: 6
    two_b:
        tfiib_data: ../spt6-data-integration/datavis/spreading-ssa4/spreading-ssa4_TFIIB-ChIP-nexus-protection.tsv.gz
        height: 6
        width: 8
    # TFIIB browser view and ChIP-qPCR
    two_c:
        vam6_tfiib_nexus_path: ../spt6-data-integration/browser-shots/VAM6/VAM6_TFIIB-ChIP-nexus-protection.tsv.gz
        # vam6_tfiib_plus: ../spt6-data-integration/browser-shots/VAM6/VAM6_TFIIB-ChIP-nexus-sense.tsv.gz
        # vam6_tfiib_minus: ../spt6-data-integration/browser-shots/VAM6/VAM6_TFIIB-ChIP-nexus-antisense.tsv.gz
        flo8_tfiib_nexus_path: ../spt6-data-integration/browser-shots/FLO8/FLO8_TFIIB-ChIP-nexus-protection.tsv.gz
        vam6_tss_sense_path: ../spt6-data-integration/browser-shots/VAM6/VAM6_TSS-seq-sense.tsv.gz
        flo8_tss_sense_path: ../spt6-data-integration/browser-shots/FLO8/FLO8_TSS-seq-sense.tsv.gz
        qpcr_data: ../small-data/tfiib-chip-qpcr/tfiib-qpcr.tsv
        annotation:
            - ../spt6-data-integration/browser-shots/VAM6/VAM6.bed
            - ../spt6-data-integration/browser-shots/FLO8/FLO8.bed
        height: 17/2
        width: 17.4*(2/3)
    # TFIIB browser view and ChIP-qPCR
    two_extra:
        avt2_tfiib_nexus_path: ../spt6-data-integration/browser-shots/AVT2/AVT2_TFIIB-ChIP-nexus-protection.tsv.gz
        ypt52_tfiib_nexus_path: ../spt6-data-integration/browser-shots/YPT52/YPT52_TFIIB-ChIP-nexus-protection.tsv.gz
        avt2_tss_sense_path: ../spt6-data-integration/browser-shots/AVT2/AVT2_TSS-seq-sense.tsv.gz
        ypt52_tss_sense_path: ../spt6-data-integration/browser-shots/YPT52/YPT52_TSS-seq-sense.tsv.gz
        qpcr_data: ../small-data/tfiib-chip-qpcr/tfiib-qpcr.tsv
        annotation:
            - ../spt6-data-integration/browser-shots/AVT2/AVT2.bed
            - ../spt6-data-integration/browser-shots/YPT52/YPT52.bed
        height: 17/2
        width: 17.4*(2/3)
    # TSS-seq vs TFIIB fold-change
    two_d:
        genic: ../tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-genic.tsv
        intragenic: ../tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-intragenic.tsv
        antisense: ../tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-antisense.tsv
        width: 14
        height: 6
    # TFIIB scatterplots
    supp_height: 24
    supp_width: 17.4
    supp_a:
        tfiib_data: ../chipnexus-tfiib/qual_ctrl/scatter_plots/tfiib-chipnexus_union-bedgraph-libsizenorm-window-200-allsamples.tsv.gz
        height: "17/12*4"
        width: 12
    # scatterplots vs. exo
    supp_b:
        data_path: ../other-datasets/rhee12/correlations/union-bedgraph-TFIIB-window-200.tsv.gz
        height: 6
        width: 10
    # metagene aligned by TATA
    supp_c:
        sense_tfiib_data: ../chipnexus-tfiib/datavis/rhee2012cleaned/libsizenorm/rhee2012cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-SENSE.tsv.gz
        antisense_tfiib_data: ../chipnexus-tfiib/datavis/rhee2012cleaned/libsizenorm/rhee2012cleaned-allsamples-allannotations-tfiib-chipnexus-libsizenorm-ANTISENSE.tsv.gz
        annotation: ../genome/annotations/rhee2012/rhee2012_cleaned.bed
        height: 4
        width: 5
    # TFIIB Western
    supp_d:
        data: ../small-data/tfiib-western/TFIIB_DST1.csv
        image: ../small-data/tfiib-western/tfiib_western_image.png
        height: 7
        width: 5

figure_three:
    height: 15
    width: 8.5
    ## NET-seq metagene
    three_a:
        sense_netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-TSS/libsizenorm/verified-transcripts-nonoverlapping-TSS-allsamples-allannotations-libsizenorm-5end-SENSE.tsv.gz
        antisense_netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-TSS/libsizenorm/verified-transcripts-nonoverlapping-TSS-allsamples-allannotations-libsizenorm-5end-ANTISENSE.tsv.gz
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping.bed
        height: 4.25
        width: 6
    # NET-seq fold change versus Spt6 levels
    three_b:
        netseq_results: ../murawska-net-seq/diff_exp/spt6-1004-37C-v-WT-37C/spt6-1004-37C-v-WT-37C-results-libsizenorm-all.tsv
        annotation: ../genome/annotations/verified-transcripts-Spt6nexus-quintiles/verified-transcripts-Spt6nexus-levels.bed
        height: 4.5
        width: 8
    # antisense scatterplots vs set2
    three_c:
        data_path: ../other-datasets/set2_spt6_netseq_antisense/antisense_window_signals/antisense-windows-allsamples.tsv.gz
        height: 6
        width: 10
    # antisense NET-seq metagenes
    three_c_alt:
        netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-scaled/libsizenorm/verified-transcripts-nonoverlapping-scaled-allsamples-allannotations-libsizenorm-5end-ANTISENSE.tsv.gz
        height: 6
        width: 8
    # NETseq scatterplots
    supp_height: 24
    supp_width: 17.4
    supp_a:
        netseq_data: ../murawska-net-seq/coverage/libsizenorm/union-bedgraph-window-200-libsizenorm.tsv.gz
        height: "17/12*8"
        width: 17.4
    supp_b:
        sense_netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/libsizenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-libsizenorm-5end-SENSE.tsv.gz
        antisense_netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-slopR300-TSS/libsizenorm/verified-transcripts-nonoverlapping-slopR300-TSS-allsamples-allannotations-libsizenorm-5end-ANTISENSE.tsv.gz
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping_slopR300.bed
        height: 5/12*17
        width: 6
    supp_c:
        data_path: ../spt6-rnapii-norm-chipnexus/coverage/window-200-libsizenorm.tsv.gz
        height: "17/12*4"
        width: 12

figure_four:
    height: 16
    width: 17.4
    # MNase-seq metagene
    four_a:
        mnase_data: ../viktorovskaya-mnase-seq/datavis/verified-transcripts-plusonenuc/spikenorm/verified-transcripts-plusonenuc-allsamples-allannotations-midpoint-spikenorm.tsv.gz
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-plus-one-nuc-dyad.bed
        height: 4.25
        width: 6
    # MNase heatmap sorted by NET-seq, and heatmaps of occupancy and fuzziness
    four_b:
        netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-TSS-NETseq-sort/libsizenorm/verified-transcripts-nonoverlapping-TSS-NETseq-sort-allsamples-allannotations-libsizenorm-5end-SENSE.tsv.gz
        mnase_data: ../viktorovskaya-mnase-seq/datavis/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort/spikenorm/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort-allsamples-allannotations-midpoint-spikenorm.tsv.gz
        quant_data: ../viktorovskaya-mnase-seq/nucleosome_calling/regions/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort/spikenorm/spt6-1004-37C-v-WT-37C/verified-transcripts-nonoverlapping-plusonenuc-NETseq-sort-allannotations-integrated-spikenorm.tsv
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping-NETseq-sort-plusone-nucdyad.bed
        height: 8.5
        width: 17.4
          # MNase heatmap sorted by TFIIB ChIP-nexus, and heatmaps of occupancy and fuzziness
    four_b_extra:
        netseq_data: ../murawska-net-seq/datavis/verified-transcripts-nonoverlapping-TSS-TFIIB-sort/libsizenorm/verified-transcripts-nonoverlapping-TSS-TFIIB-sort-allsamples-allannotations-libsizenorm-5end-SENSE.tsv.gz
        mnase_data: ../viktorovskaya-mnase-seq/datavis/verified-transcripts-nonoverlapping-plusonenuc-TFIIB-sort/spikenorm/verified-transcripts-nonoverlapping-plusonenuc-TFIIB-sort-allsamples-allannotations-midpoint-spikenorm.tsv.gz
        quant_data: ../viktorovskaya-mnase-seq/nucleosome_calling/regions/verified-transcripts-nonoverlapping-plusonenuc-TFIIB-sort/spikenorm/spt6-1004-37C-v-WT-37C/verified-transcripts-nonoverlapping-plusonenuc-TFIIB-sort-allannotations-integrated-spikenorm.tsv
        annotation: ../genome/annotations/Scer_transcripts_w_verifiedORFs-nonoverlapping-WT-TFIIB-sort.bed
        height: 8.5
        width: 17.4
    # MNase global occupancy and fuzziness quantification
    four_c:
        wt_mnase_quant: ../viktorovskaya-mnase-seq/nucleosome_calling/spt6-1004-37C-v-WT-37C/spikenorm/pooled/nucleosome_calling_data_WT-37C.Fnor.smooth.positions.xls
        spt6_mnase_quant: ../viktorovskaya-mnase-seq/nucleosome_calling/spt6-1004-37C-v-WT-37C/spikenorm/pooled/nucleosome_calling_data_spt6-1004-37C.Fnor.smooth.positions.xls
        height: 4.25
        width: 6
    # MNase-seq browser shot and H3 ChIP-qPCR
    four_d:
        vam6_mnase_path: ../spt6-data-integration/browser-shots/VAM6/VAM6_MNase-seq-smoothed.tsv.gz
        qpcr_data: ../small-data/h3-chip-qpcr/h3-qpcr.tsv
        annotation: ../spt6-data-integration/browser-shots/VAM6/VAM6.bed
        height: 10
        width: 8
    # MNase-seq scatterplots
    supp_height: 20
    supp_width: 17.4
    supp_a:
        mnase_data: ../viktorovskaya-mnase-seq/coverage/spikenorm/union-bedgraph-window-75-spikenorm.tsv.gz
        height: 6
        width: 10
    # MNase metagenes by NET-seq levels
    supp_b:
        mnase_data: ../viktorovskaya-mnase-seq/datavis/verified-transcripts-nonoverlapping-plusonenuc-NETseq-quintiles/spikenorm/verified-transcripts-nonoverlapping-plusonenuc-NETseq-quintiles-allsamples-allannotations-midpoint-spikenorm.tsv.gz
        annotation:
            - ../genome/annotations/verified-transcripts-nonoverlapping-NETseq-quintiles-plusonenucdyad/Scer_transcripts_w_verifiedORFs-nonoverlapping-plusone-nucdyad-NETseq-quintile-1.bed
            - ../genome/annotations/verified-transcripts-nonoverlapping-NETseq-quintiles-plusonenucdyad/Scer_transcripts_w_verifiedORFs-nonoverlapping-plusone-nucdyad-NETseq-quintile-2.bed
            - ../genome/annotations/verified-transcripts-nonoverlapping-NETseq-quintiles-plusonenucdyad/Scer_transcripts_w_verifiedORFs-nonoverlapping-plusone-nucdyad-NETseq-quintile-3.bed
            - ../genome/annotations/verified-transcripts-nonoverlapping-NETseq-quintiles-plusonenucdyad/Scer_transcripts_w_verifiedORFs-nonoverlapping-plusone-nucdyad-NETseq-quintile-4.bed
            - ../genome/annotations/verified-transcripts-nonoverlapping-NETseq-quintiles-plusonenucdyad/Scer_transcripts_w_verifiedORFs-nonoverlapping-plusone-nucdyad-NETseq-quintile-5.bed
        height: 8
        width: 8
    supp_c:
        pma1_mnase: ../spt6-data-integration/browser-shots/PMA1/PMA1_MNase-seq-smoothed.tsv.gz
        hsp82_mnase: ../spt6-data-integration/browser-shots/HSP82/HSP82_MNase-seq-smoothed.tsv.gz
        qpcr_data: ../small-data/h3-chip-qpcr/h3-qpcr.tsv
        height: 8
        width: 8

figure_five:
    height: 16
    width: 17.4
    five_a:
        annotation:
            - ../cluster_intragenic_mnase/spt6-1004-37C-induced-intragenic-MNase-cluster-1.bed
            - ../cluster_intragenic_mnase/spt6-1004-37C-induced-intragenic-MNase-cluster-2.bed
        mnase_data: ../spt6-data-integration/datavis/mnase-clustering/mnase-clustering_MNase-seq.tsv.gz
        # rnapii_data: ../spt6-data-integration/datavis/mnase-clustering/mnase-clustering_RNAPII-ChIP-nexus.tsv.gz
        # spt6_data: ../spt6-data-integration/datavis/mnase-clustering/mnase-clustering_Spt6-ChIP-nexus.tsv.gz
        gc_data: ../spt6-data-integration/datavis/mnase-clustering/mnase-clustering_GC-pct.tsv.gz
        height: 10
        width: 8
    five_b:
        cluster_one: ../cluster_intragenic_mnase/spt6-1004-37C-induced-intragenic-MNase-cluster-1.bed
        cluster_two: ../cluster_intragenic_mnase/spt6-1004-37C-induced-intragenic-MNase-cluster-2.bed
        tss_diffexp: ../tss-seq/diff_exp/spt6-1004-37C-v-WT-37C/spikenorm/intragenic/spt6-1004-37C-v-WT-37C_tss-seq-spikenorm-diffexp-results-intragenic-up.tsv
        tfiib_diffbind: ../tss-v-tfiib-nexus/diff_binding/spt6-1004-37C-v-WT-37C-tfiib-window-results-intragenic.tsv
        height: 7
        width: 6
    # sequence logos
    five_c:
        data_paths:
            - ../tss-seq/seq_logos/spt6-1004-37C/spt6-1004-37C-genic-seqlogo.tsv
            - ../tss-seq/seq_logos/spt6-1004-37C/spt6-1004-37C-intragenic-seqlogo.tsv
        height: 4
        width: 6
    # intragenic TATA boxes
    five_d:
        tata_genic: ../motif_analysis_tata/comparisons/all-genic-v-random/all-genic-v-random_condition_allFIMOresults.tsv.gz
        tata_intragenic: ../motif_analysis_tata/comparisons/all-intragenic-v-random/all-intragenic-v-random_condition_allFIMOresults.tsv.gz
        tata_random: ../motif_analysis_tata/comparisons/all-intragenic-v-random/all-intragenic-v-random_control_allFIMOresults.tsv.gz
        height: 4.5
        width: 8
    five_e:
        all_motif_path: ../motif_analysis_allmotifs/comparisons/all-intragenic-v-random/all-intragenic-v-random_motif-enrichment.tsv
        height: 9
        width: 8

figure_six:
    height: 16
    width: 17.4
    six_a:
        pma1_tfiib_nexus: ../spt6-data-integration/browser-shots/PMA1/PMA1_TFIIB-ChIP-nexus-protection.tsv.gz
        # pma1_tss_sense: ../spt6-data-integration/browser-shots/PMA1/PMA1_TSS-seq-sense.tsv.gz
        pma1_mnase: ../spt6-data-integration/browser-shots/PMA1/PMA1_MNase-seq-smoothed.tsv.gz
        hsp82_tfiib_nexus: ../spt6-data-integration/browser-shots/HSP82/HSP82_TFIIB-ChIP-nexus-protection.tsv.gz
        # hsp82_tss_sense: ../spt6-data-integration/browser-shots/HSP82/HSP82_TSS-seq-sense.tsv.gz
        hsp82_mnase: ../spt6-data-integration/browser-shots/HSP82/HSP82_MNase-seq-smoothed.tsv.gz
        qpcr_data_path: ../small-data/tfiib-chip-qpcr/tfiib-qpcr.tsv
        height: 10
        width: 16
    six_b:
        mnase_data: ../spt6-data-integration/datavis/spt6-genic-TSSs/spt6-genic-TSSs_MNase-seq.tsv.gz
        height: 10
        width: 8
    # six_c:
    #     go_results: ../tss-seq/gene_ontology/spt6-1004-37C-v-WT-37C/spikenorm/genic/spt6-1004-37C-v-WT-37C-GO-spikenorm-up-genic-results.tsv
    #     height: 4.5
    #     width: 9.5
    six_c:
        spt6_blot_path: ../small-data/spt6-depletion-ssa4-rtqpcr/Spt6-AID-blot.png
        pgk1_blot_path: ../small-data/spt6-depletion-ssa4-rtqpcr/Pgk1-blot.png
        # data_path: ../small-data/spt6-depletion-ssa4-rtqpcr/spt6_depletion_RTqPCR.tsv
        data_path: ../small-data/spt6-depletion-ssa4-rtqpcr/spt6_depletion_RTqPCR_experiment2.tsv
        height: 8
        width: 10
